version: "3"

services:
  server:
    container_name: html
    image: nginx:latest
    volumes:
    - ./:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:html.virtualsync.net"
    networks:
    - mynet


networks:
  mynet:
    external:
      name: proxy-server-network
